// Created by iWeb 3.0.4 local-build-20180126

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,-1,1,389),url:'Writing_files/stroke.png'},{rect:new IWRect(-2,-2,1,1),url:'Writing_files/stroke_1.png'},{rect:new IWRect(-1,-2,293,1),url:'Writing_files/stroke_2.png'},{rect:new IWRect(292,-2,1,1),url:'Writing_files/stroke_3.png'},{rect:new IWRect(292,-1,1,389),url:'Writing_files/stroke_4.png'},{rect:new IWRect(292,388,1,1),url:'Writing_files/stroke_5.png'},{rect:new IWRect(-1,388,293,1),url:'Writing_files/stroke_6.png'},{rect:new IWRect(-2,388,1,1),url:'Writing_files/stroke_7.png'}],new IWSize(291,387)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,-1,1,422),url:'Writing_files/stroke_8.png'},{rect:new IWRect(-2,-2,1,1),url:'Writing_files/stroke_9.png'},{rect:new IWRect(-1,-2,281,1),url:'Writing_files/stroke_10.png'},{rect:new IWRect(280,-2,1,1),url:'Writing_files/stroke_11.png'},{rect:new IWRect(280,-1,1,422),url:'Writing_files/stroke_12.png'},{rect:new IWRect(280,421,1,1),url:'Writing_files/stroke_13.png'},{rect:new IWRect(-1,421,281,1),url:'Writing_files/stroke_14.png'},{rect:new IWRect(-2,421,1,1),url:'Writing_files/stroke_15.png'}],new IWSize(279,419))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Writing_files/WritingMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');fixAllIEPNGs('Media/transparent.gif');Widget.onload();applyEffects()}
function onPageUnload()
{Widget.onunload();}
