// Created by iWeb 3.0.4 local-build-20170319

setTransparentGifURL('../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-2,-1,1,184),url:'Blog_files/stroke_16.png'},{rect:new IWRect(-2,-2,1,1),url:'Blog_files/stroke_17.png'},{rect:new IWRect(-1,-2,142,1),url:'Blog_files/stroke_18.png'},{rect:new IWRect(141,-2,1,1),url:'Blog_files/stroke_19.png'},{rect:new IWRect(141,-1,1,184),url:'Blog_files/stroke_20.png'},{rect:new IWRect(141,183,1,1),url:'Blog_files/stroke_21.png'},{rect:new IWRect(-1,183,142,1),url:'Blog_files/stroke_22.png'},{rect:new IWRect(-2,183,1,1),url:'Blog_files/stroke_23.png'}],new IWSize(140,182)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,83),url:'Blog_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Blog_files/stroke_1.png'},{rect:new IWRect(1,-1,158,2),url:'Blog_files/stroke_2.png'},{rect:new IWRect(159,-1,2,2),url:'Blog_files/stroke_3.png'},{rect:new IWRect(159,1,2,83),url:'Blog_files/stroke_4.png'},{rect:new IWRect(159,84,2,2),url:'Blog_files/stroke_5.png'},{rect:new IWRect(1,84,158,2),url:'Blog_files/stroke_6.png'},{rect:new IWRect(-1,84,2,2),url:'Blog_files/stroke_7.png'}],new IWSize(160,85)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,-1,1,111),url:'Blog_files/stroke_8.png'},{rect:new IWRect(-2,-2,1,1),url:'Blog_files/stroke_9.png'},{rect:new IWRect(-1,-2,117,1),url:'Blog_files/stroke_10.png'},{rect:new IWRect(116,-2,1,1),url:'Blog_files/stroke_11.png'},{rect:new IWRect(116,-1,1,111),url:'Blog_files/stroke_12.png'},{rect:new IWRect(116,110,1,1),url:'Blog_files/stroke_13.png'},{rect:new IWRect(-1,110,117,1),url:'Blog_files/stroke_14.png'},{rect:new IWRect(-2,110,1,1),url:'Blog_files/stroke_15.png'}],new IWSize(115,109))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function photocastSubscribe()
{photocastHelper("http://michellemcbeth.com/michellemcbeth.com/Blog/rss.xml");}
function onPageLoad()
{loadMozillaCSS('Blog_files/BlogMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');detectBrowser();fixAllIEPNGs('../Media/transparent.gif');Widget.onload();fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
